
### Get all categories
GET localhost:3000/api/categories
Accept: application/json

### Create new Category
POST localhost:3000/api/categories
Accept: application/json
Content-Type: application/json

{
  "name": "Computer"
}

### Get category by id
GET localhost:3000/api/categories/10
Accept: application/json

### Update category by id
PUT localhost:3000/api/categories/2
Accept: application/json
Content-Type: application/json

{
  "name": ""
}


### DELETE category
DELETE localhost:3000/api/categories/3
Accept: application/json
